import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SideBarIcon from "@/components/sidebar/SideBarIcon";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      cz-shortcut-listen="true"
    >
      <body className="h-full w-full relative bg-black p-2">
        {/* Navbar */}
        <div id="Navbar" className="fixed w-full p-4">
          <SideBarIcon />
        </div>

        {/* Main Content */}
        <div className="h-full">{children}</div>
      </body>
    </html>
  );
}
